POST http://localhost:8080/api/channels
Content-Type: application/json
Accept: application/json

{
  "name": "full-config-channel",
  "input": {
    "url": "rtsp://example.com/full",
    "avioflags": "direct",
    "probesize": 1000000,
    "analyzeduration": 500000,
    "fflags": "nobuffer",
    "max_delay": 500,
    "localaddr": "192.168.1.5",
    "timeout": 5000000,
    "rtsp_transport": "tcp"
  },
  "output": {
    "url": "/tmp/output.ts",
    "localaddr": "192.168.1.10",
    "pkt_size": 2048,
    "map_video": false,
    "map_audio": true,
    "map_data": false,
  },
  "enabled": false,
  "restartSec": 10
}
