// full_update_patch.http
PATCH http://localhost:8080/api/channels/42
Content-Type: application/merge-patch+json

{
  "name": "Live1",
  "source": {
    "url": "rtsp://172.16.5.20/live.sdp",
    "auth": {
      "username": "zmuxUser",
      "password": "Aa1234!@#$"
    }
  },
  "enabled": true
}
