// update_name_and_source_patch.http
// assumes request sent after full_update_patch.http and needs to clear auth
PATCH http://localhost:8080/api/channels/42
Content-Type: application/merge-patch+json

{
  "name": "Live2",
  "input": {
    "url": "rtsp://203.0.113.45:5544/streaming/video1",
    "auth": null
  }
}
